deploy:
  distributions: sdist bdist_wheel
  'on': {repo: timmartin19/ultra-config, tags: true}
  password:
    secure: !!binary |
      ZGY5R3BYWkhUWnNmU3JHRWU3QUY1NHNkb3RQNjlkZkFaY2srcEZjZ0V5aW9NRkNzU3ZGWE1vdFhq
      dnRQNWhVeEdHd3VTcDlmbUwrUEFiV2NWQ2YrOHBWZ3ZwYjM2NS9uRllGaVYzdktiVXBWTFlmekdV
      VHJFUmwya1crNFNEWjJpdUdWWGJLN0E5YXJ3RUswb2x6ekowRUJpMGJCUjRuVXU0VG5NSmlNb3F5
      cDJyRTZPbG93UzdPbWNJdC92M29yNFRNdkE1bVV2STJOTGlCSXFUN0pnODBjWWQ5cjQ2U2NFMGR4
      SnR0QW5SUlJTdzRyTlIrcEYxL0c4UU84eHZSR2Yvc1RVY2NJbzVHU0I2RWtnWitlWDVSUlNoNVp3
      UXpSNXJnTDFrVW50eVNLcDlKdnpDYTlhdjBqZXZBNHBqb3ROb0dzcUNUZ1JWK3FnK3M3NU9abmQx
      UjBGWFJqc1dXV1ZhVUJCUTZMeEM3SkRmM3k4Z1VRS3VxQzBaOGFyVFF5UnBCMWNoK21zTWo3RUJh
      M2FqRUhmaWNGc2RiTE5xTlVVbWJrSDZ6RnJJN3o5dFRkYy9pMXVIOTFORHdyaGx5VEFhNURjeGhJ
      Y3pQUVlNYm1TcTQxejFTcVkyUmVVQnkwQVpTckM1Uk94bDRyT2FuVjAxZkdhUnFXa2JkOEMwNlhT
      MzE2MUpad2VCZTRJV1ZFQWFNaU9sOGdGQWgwU2ZPWlB1S2drb2FnZjd5NG5sUVhkenhOdm5aaHF4
      UXNtblc4Tk9INWI1YVBGUmNQRFlVakFXMk5naTJsRzFVUU9WdDRUKytXUzRaeDlZekpodGhITk9V
      UG5Zb2NEelIxN2lSdjd4aFNnR2s4MDhjYmZBb3VSUmM0Z3dIWVdPRlhMc1VoeXRQeHk5bG1aMjg9
  provider: pypi
  user: timmartin19
language: python
script: python -m unittest discover
python: [3.5, 3.4, 2.7]
after_success: ['bash <(curl -s https://codecov.io/bash)']
